name: "Test and coverage check"
description: "Test and coverage check with gcovr, pass if coverage is greater than 20%"

runs:
  using: "composite"
  steps:
    - name: "Run coverage"
      shell: bash
      run: |
        PROJECT_PATH=$(pwd)

        # ToDo: Add documentation and describe better this command
        # This command generate a output if the test fail
        # the --test-dir specify the path where are include the test
        # See: https://cmake.org/cmake/help/latest/manual/ctest.1.html
        ctest --test-dir build/tests --output-on-failure

        # ToDo: Add documentation and describe better this command
        # This command using gcovr generate a coverage report
        # option -r is the root directory of source files ($PROJECT_PATH .) where . is the current directory
        # Report is save in the file coverage.txt 
        # See: man gcovr in terminal
        gcovr -r $PROJECT_PATH . > $PROJECT_PATH/coverage.txt

        echo "Runnig: gcovr -r $PROJECT_PATH ."

        cat $PROJECT_PATH/coverage.txt

        # Find the value of correct coverage
        # ToDo: Add documentation and describe better this command
        # This command save the result of the percent of TOTAL Coverage
        # The value is obtained from the file coverage.txt in the line that include TOTAL
        # Just before symbol %.
        COVERAGE_RESULT=$(grep "TOTAL" $PROJECT_PATH/coverage.txt | awk '{print $NF}' | cut -d '%' -f 1)

        # Coverage lines GT 20
        # This compare the value of COVERAGE_RESULT with the minimum percent of coverage permit.
        if [ "$(echo "$COVERAGE_RESULT > 20" | bc)" -eq 1 ]; then
            echo "Coverage is greater than 20%. Nice!"
            exit 0
        else
            echo "Error: Coverage is less than or equal to 20%"
            exit 1
        fi

    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Tests or coverage errors!!!
        path: $(pwd)/error_flag.txt
        retention-days: 1
